networks:
  qkd:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.8.0/24

services:
  bob:
    image: bob
    build:
      context: .
      dockerfile: c/DockerfileBob #Change depends of the version you want to try
    container_name: bob
    environment:
      ACCOUNT_ID: "3009" #Account id from https://qukaydee.com
      CERT_DIR: "/app/"
      SAE_ID: 1
    hostname: bob
    networks: 
      qkd:
        ipv4_address: 192.168.8.2

  alice:
    image: alice
    build:
      context: .
      dockerfile: c/DockerfileAlice #Change depends of the version you want to try
    container_name: alice
    hostname: alice
    environment:
      ACCOUNT_ID: "3009" #Account id from https://qukaydee.com
      CERT_DIR: "/app/"
      SAE_ID: 2
    networks: 
      qkd:
        ipv4_address: 192.168.8.3

