networks:
  qkd:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.8.0/24 # Define un rango de subred para esta red

services:
  bob:
    image: bob
    build:
      context: .
      dockerfile: DockerfileBob
    container_name: bob
    environment:
      ACCOUNT_ID: "3009"
      CERT_DIR: "/app/"
      SAE_ID: 1
    hostname: bob
    networks: 
      qkd:
        ipv4_address: 192.168.8.2 # IP estática

  alice:
    image: alice
    build:
      context: .
      dockerfile: DockerfileAlice
    container_name: alice
    hostname: alice
    environment:
      ACCOUNT_ID: "3009"
      CERT_DIR: "/app/"
      SAE_ID: 2
    networks: 
      qkd:
        ipv4_address: 192.168.8.3 # IP estática

